media-user-token: "Ai1TM51xrMasKHwAPVFKTwmkZ+anCYWlyh2AO2qSSlnlezUU5SIsjEtRa16FxUdq0LPTamqajD8rTEh71X3Xe71ARFN6P3wT+9+bw51N2TRWMkrepkz48xWYoNgp3u9arXvKo5/cONWzIXJai8yBwODq48OdbZ88ruYloFGghnhLSJrOEJc01/TS72g7Fvfdule9UaHRu0aDzCYbAJdB/gdghsDtWkT4aa6BZvTEtgNyRbL9/Q=="
language: ""
lrc-type: "lyrics"
lrc-format: "lrc"
embed-lrc: true
save-lrc-file: true
save-artist-cover: false
save-animated-artwork: false
emby-animated-artwork: false
embed-cover: true
cover-size: 5000x5000
cover-format: jpg
alac-save-folder: E:\Music
atmos-save-folder: E:\Music
aac-save-folder: E:\Music
max-memory-limit: 256
decrypt-m3u8-port: "127.0.0.1:10020"
get-m3u8-port: "127.0.0.1:20020"
get-m3u8-from-device: true
get-m3u8-mode: hires
aac-type: aac-lc
alac-max: 192000
atmos-max: 2768
limit-max: 200
album-folder-format: "{AlbumName}"
playlist-folder-format: "{PlaylistName}"
song-file-format: "{SongNumer}. {SongName}"
artist-folder-format: "{UrlArtistName}"
explicit-choice: "[E]"
clean-choice: "[C]"
apple-master-choice: "[M]"
use-songinfo-for-playlist: true
dl-albumcover-for-playlist: true
mv-audio-type: atmos
mv-max: 2160
storefront: "cn"
convert-after-download: true
convert-format: "flac"
convert-keep-original: true
convert-skip-if-source-matches: false
ffmpeg-path: "./ffmpeg.exe"
mp4box-path: "D:/GPAC/MP4Box.exe"
convert-extra-args: ""
convert-extra-formats:
- mp3